---
- name: Deploy MERN Application
  hosts: all
  become: true
  vars:
    ansible_become_pass: "12345678"

  tasks:
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "{{ playbook_dir }}/docker-compose.yml"

    - name: Run Docker Compose
      command: docker-compose up -d
