apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bansalc73/backend-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 5000
        env: 
        - name: MONGO
          valueFrom:
            secretKeyRef:
              name: mern-backend-secret
              key: MONGO
        - name: JWT
          valueFrom:
            secretKeyRef:
              name: mern-backend-secret
              key: JWT
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
